Added Unique Localized Text Catalog Identification section to volume 3
IHE/DEV.SDPi pull request #344
Opened 2024-11-29 08:07 UTC by PeterKranich

## 📑 Description

Added Unique Localized Text Catalog Identification section to volume 3.

Proposal is to add the text catalog id and version to the MDS/ProductionSpecification.

## ☑ Mandatory Tasks

The following aspects have been respected by the pull request assignee and at least one reviewer:
  
- Changelog update (necessity checked and entry added or not added respectively)
  * [ ] Pull Request Assignee
  * [ ] Reviewer

2024-11-29 08:12 UTC, PeterKranich commented
@d-gregorczyk: if you agree with my proposal, we need to define the codes for entries in the ProductionSpecification for the text catalog id and version. I have not found appropriate codes in the Rosetta DB.  There are two codes which may fit but I am not sure:

Status: Published
RefID: MDC_ATTR_LOCALIZN
Term Code: 1::2359
Context Free Code: 67895
Description/Definition:
DIM Name: Localization

Status: Published
RefID: MDC_ATTR_VMS_MDS_LOCALIZN
Term Code: 1::2470
Context Free Code: 68006
Description/Definition:
DIM Name: Mds_localization

2024-11-29 14:31 UTC, ToddCooper commented
**SDPi Friday 2024.11.29 Review** - 

1. @mfaughn verified that the two MDC_ codes above were in the first version of the -10101 nomenclature, but the definitions are ... thin.
2. **MDC_ATTR_VMS_MDS_TEXT_CAT** (1::2472) - Annex B #defines of -10101 + in RTMMS ... but NO DEFINITION!
3. Value:  ID + version (e.g., OID/URN::OID::12345) 

@PeterKranich  - Propose a definition for the _TEXT_CAT term.

2024-12-13 15:05 UTC, ToddCooper commented
SDPi Friday 2024.12.13 Review - 

Discussion issues included:

1. BICEPS does not have a concept of "text catalog", which should be added to this text 
2. Current content needs some editorial updates (e.g., capitalization, more detail in examples, etc.)
3. Provide background for how this works in conjunction ("under the hood") with the LOCALIZATION SERVICE

2024-12-18 08:25 UTC, d-gregorczyk commented on asciidoc/volume3/biceps-content-module/tf3-ch-8.3.2.9.8-localized-text-catalog-identification.adoc
> +In <<acronym_biceps>>, localized texts for parameter labels, alert strings, enumerations, etc. can be retrieved with the provided *LocalizedText/@ref* (text id) and language code from the <<acronym_b
```suggestion
In <<acronym_biceps>>, localized texts for parameter labels, alert strings, enumerations, etc. can be retrieved with the provided *LocalizedText/@Ref* (text id) and language code from the <<acronym_biceps>> Localization Service.

```

2024-12-18 08:25 UTC, d-gregorczyk commented on asciidoc/volume3/biceps-content-module/tf3-ch-8.3.2.9.8-localized-text-catalog-identification.adoc
> +In <<acronym_biceps>>, localized texts for parameter labels, alert strings, enumerations, etc. can be retrieved with the provided *LocalizedText/@ref* (text id) and language code from the <<acronym_b
```suggestion
In <<acronym_biceps>>, localized texts for parameter labels, alert strings, enumerations, etc. can be retrieved with the provided *LocalizedText/@ref* (text id) and language code from the <<acronym_biceps>> LOCALIZATION SERVICE.

```

2024-12-18 08:25 UTC, d-gregorczyk commented on asciidoc/volume3/biceps-content-module/tf3-ch-8.3.2.9.8-localized-text-catalog-identification.adoc
> +A <<actor_somds_provider>> that has implemented the *<<acronym_biceps>> LOCALIZATION SERVICE* and supports versioning of the text catalog should provide a unique version number concatenated with the
This requirement is too weak to have a significant effect on interoperability.

2024-12-18 08:25 UTC, d-gregorczyk commented on asciidoc/volume3/biceps-content-module/tf3-ch-8.3.2.9.8-localized-text-catalog-identification.adoc
> +NOTE: The version number can be part of unique text catalog identifier, e. g. the last sub-node of the *OID*. In this case, the requirement does not apply.
According to the requirement, that is exactly how it is not supposed to be modelled as such an identifier would lack the double colon, right?

2024-12-18 08:25 UTC, d-gregorczyk commented on asciidoc/volume3/biceps-content-module/tf3-ch-8.3.2.9.8-localized-text-catalog-identification.adoc
> +A <<actor_somds_provider>> that provides a unique text catalog identifier in the *pm:MdsDescriptor+++<wbr/>+++/pm:ProductionSpecification* list but does not support versioning of the text catalog sha
"A provider that does not support versioning of text catalogs shall provide a new identifier for each new version" sounds  odd. If versioning is not supported, there is no need to generate new identifiers.

2025-03-04 06:35 UTC, PeterKranich commented on asciidoc/volume3/biceps-content-module/tf3-ch-8.3.2.9.8-localized-text-catalog-identification.adoc
> +[#vol3_clause_localized_text_catalog_identification]
I agree it is more an optimization which helps the consumers when they have to manage devices which all use the same text catalog.
Where would you place recommendations? Also in Vol 3 same section?

2025-03-04 06:39 UTC, PeterKranich commented on asciidoc/volume3/biceps-content-module/tf3-ch-8.3.2.9.8-localized-text-catalog-identification.adoc
> +A <<actor_somds_provider>> that has implemented the *<<acronym_biceps>> LOCALIZATION SERVICE* and supports versioning of the text catalog should provide a unique version number concatenated with the
I can change this to best practice recommendations.

2025-03-04 06:43 UTC, PeterKranich commented on asciidoc/volume3/biceps-content-module/tf3-ch-8.3.2.9.8-localized-text-catalog-identification.adoc
> +NOTE: The version number can be part of unique text catalog identifier, e. g. the last sub-node of the *OID*. In this case, the requirement does not apply.
Yes, when the versioning is already part of the OID (for each new text catalog version there is a new OID) this requirement will not apply

2025-03-04 06:46 UTC, PeterKranich commented on asciidoc/volume3/biceps-content-module/tf3-ch-8.3.2.9.8-localized-text-catalog-identification.adoc
> +A <<actor_somds_provider>> that provides a unique text catalog identifier in the *pm:MdsDescriptor+++<wbr/>+++/pm:ProductionSpecification* list but does not support versioning of the text catalog sha
This is the case, when there is no explicit versioning available for a text catalog. When the text catalog has been changed but there is no versioning, the only way for the consumer to get aware of a changed text catalog is a new text catalog identifier.

2025-03-11 15:05 UTC, d-gregorczyk commented
Missing pieces:

- Definition of text catalog. There is no definition of "text catalog" whatsoever neither in BICEPS nor in SDPi.
- Definition of text ids / text catalog identifiers - terms are used interchangeably and need to be defined and used consistently (at least if they mean the same)

2025-03-11 15:06 UTC, d-gregorczyk requested changes

2025-03-11 15:06 UTC, d-gregorczyk commented on asciidoc/volume3/biceps-content-module/tf3-ch-8.3.2.9.8-localized-text-catalog-identification.adoc
> +[#vol3_clause_localized_text_catalog_identification]
I am out when it comes to positioning of contents in SDPi :-)

2025-03-11 15:06 UTC, d-gregorczyk commented on asciidoc/volume3/biceps-content-module/tf3-ch-8.3.2.9.8-localized-text-catalog-identification.adoc
> +A <<actor_somds_provider>> that has implemented the *<<acronym_biceps>> LOCALIZATION SERVICE* and supports explicit versioning of the text catalog is supposed to provide a unique version number conca
Separating by colon gets me HL7v2 vibes... We should not encourage people to do that but rather use the methods by incorporating versions in the URN.

2025-03-17 12:10 UTC, PeterKranich commented on asciidoc/volume3/biceps-content-module/tf3-ch-8.3.2.9.8-localized-text-catalog-identification.adoc
> +In <<acronym_biceps>>, localized texts for parameter labels, alert strings, enumerations, etc. can be retrieved with the provided *LocalizedText/@ref* (text id) and language code from the <<acronym_b
Fixed in next version

2025-03-17 12:11 UTC, PeterKranich commented on asciidoc/volume3/biceps-content-module/tf3-ch-8.3.2.9.8-localized-text-catalog-identification.adoc
> +In <<acronym_biceps>>, localized texts for parameter labels, alert strings, enumerations, etc. can be retrieved with the provided *LocalizedText/@Ref* (text id) and language code from the <<acronym_b
Fixed in next version

2025-03-17 12:11 UTC, PeterKranich commented on asciidoc/volume3/biceps-content-module/tf3-ch-8.3.2.9.8-localized-text-catalog-identification.adoc
> +NOTE: The unique text catalog identifier defined in the corresponding *pm:ProductionSpecification+++<wbr/>+++/pm:ProductionSpec* can be an *urn* of type *uuid* or *oid*, e. g. *"urn:oid:1.3.6.1.4.1.1
Fixed in next version

2025-03-17 13:06 UTC, PeterKranich commented on asciidoc/volume3/biceps-content-module/tf3-ch-8.3.2.9.8-localized-text-catalog-identification.adoc
> +[#vol3_clause_localized_text_catalog_identification]
OK, I leave it where it is.

2025-03-25 08:45 UTC, d-gregorczyk requested changes

2025-03-25 08:45 UTC, d-gregorczyk commented on asciidoc/volume3/biceps-content-module/tf3-ch-8.3.2.9.8-localized-text-catalog-identification.adoc
> +.Recommentation A
```suggestion
.Recommendation A
```

2025-04-04 12:29 UTC, d-gregorczyk commented
The last thing that is missing, is the changelog entry, isn't it? (why ever we marked it as done under "mandatory tasks".

2025-04-04 13:31 UTC, d-gregorczyk approved these changes

2025-04-04 13:32 UTC, merged